name: Linting

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  call_workflow:
    uses: discourse/discourse-plugin-skeleton/.github/workflows/plugin-linting-reusable.yml@main
